### ISSUE TITLE
Some books you plan to read are not written by authenticated people

### ISSUE THREAD

**Issue by stevemao** [cht8687/code-warehouse#1]
"Pro React" is written by Cássio Souza but he's not a member of any react related projects.
Similarly "JavaScript with Promises" is not written by Domenic Denicola. 
Do you think it's worth of the time? You could read books like [Eloquent JavaScript](https://github.com/marijnh/Eloquent-JavaScript) (they are written by authenticated JavaScript developers).

**Comment by cht8687** [comment]
who cares!...

**Comment by stevemao** [comment]
Mate you need to read books written by good authors :)

**Comment by cht8687** [comment]
@stevemao  that's true. I've read some and really not worth the time.
